version: '3.9'

services:
  workspace:
    build:
      context: .
    tty: true
    volumes:
      - ../:/home/vscode/workspace
  db:
    image: postgres:14
    ports:
      - 16131:5432
    volumes:
      - db_store:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=bumpofchicken

volumes:
  db_store: